export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#faf8ff",
        "primary-fixed": "#dae2ff",
        "occupancy-low": "#198754",
        "tertiary-fixed-dim": "#b3c5ff",
        "on-surface": "#191b24",
        "surface-subtle": "#F6F9FF",
        "secondary-fixed": "#ffdbcb",
        "outline": "#727787",
        "on-primary-fixed-variant": "#00419e",
        "on-tertiary-fixed": "#001849",
        "occupancy-high": "#DC3545",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#dae1ff",
        "on-primary-fixed": "#001946",
        "primary-container": "#0d6efd",
        "on-secondary-fixed-variant": "#783100",
        "chart-line-1": "#0D6EFD",
        "surface-bright": "#faf8ff",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-background": "#191b24",
        "surface-variant": "#e1e2ee",
        "on-secondary-fixed": "#341100",
        "surface": "#faf8ff",
        "primary": "#0057cd",
        "surface-container-highest": "#e1e2ee",
        "tertiary-container": "#5974be",
        "on-secondary-container": "#5c2400",
        "surface-container-high": "#e6e7f3",
        "on-error": "#ffffff",
        "occupancy-medium": "#FFC107",
        "on-tertiary-fixed-variant": "#26438a",
        "surface-container-low": "#f2f3ff",
        "secondary": "#9e4300",
        "secondary-fixed-dim": "#ffb691",
        "inverse-primary": "#b1c5ff",
        "chart-line-3": "#20C997",
        "surface-dim": "#d8d9e5",
        "error-container": "#ffdad6",
        "outline-variant": "#c2c6d8",
        "tertiary": "#405ba3",
        "primary-fixed-dim": "#b1c5ff",
        "secondary-container": "#fe761c",
        "on-primary": "#ffffff",
        "inverse-surface": "#2d3039",
        "surface-container": "#ecedf9",
        "surface-tint": "#0057ce",
        "on-surface-variant": "#424655",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eff0fc",
        "chart-line-2": "#FF771D",
        "on-tertiary-container": "#ffffff",
        "on-primary-container": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1200px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "stack-xl": "48px"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-caps": ["Inter"],
        "body-md": ["Inter"],
        "data-display": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-sm": ["Inter"]
      },
      fontSize: {
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "data-display": ["48px", { "lineHeight": "48px", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
